settings_version: 0.0.4
datasets_dir: C:\Users\Rachit\Desktop\projects\dvcon26\taod_vega\taod_vega\datasets
weights_dir: weights
runs_dir: runs
uuid: 84819f1765575cc3070a89ea807447bffb0479d2ea45004964c480f92248cc81
sync: true
api_key: ''
openai_api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
